# Generated by Django 4.0.2 on 2022-02-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
