# Generated by Django 4.0.2 on 2022-02-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
